name: CI

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: robinraju/release-downloader@v1
        id: download
        with:
          repository: 'dsyer/protobuf-wasm'
          latest: true
          fileName: protobuf-wasm.tgz
          out-file-path: downloaded

      - run: ls -l downloaded

      - uses: mymindstorm/setup-emsdk@v14

      - uses: bytecodealliance/actions/wasmtime/setup@v1

      - name: Build
        working-directory: downloaded
        run: |
          tar -zxvf ${{ fromJson(steps.download.outputs.downloaded_files)[0] }}
          tree .
          emcc -Os -I ./include -s STANDALONE_WASM ./lib/libprotobuf-c.a ./lib/libprotobuf.a -o protoc.wasm
          wasmtime protoc.wasm --version

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: protoc.wasm
          path: protobuf-wasm/protoc.wasm