name: CI

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: robinraju/release-downloader@v1
        with:
          repository: 'dsyer/protobuf-wasm'
          tarBall: true
          latest: true
          extract: true
          out-file-path: protobuf-wasm

      - uses: mymindstorm/setup-emsdk@v14

      - uses: bytecodealliance/actions/wasmtime/setup@v1

      - name: Build
        working-directory: protobuf-wasm
        run: |
          emcc -Os -I ./include -s STANDALONE_WASM -s EXPORTED_FUNCTIONS="['_main']" ./lib/libprotobuf-c.a ./lib/libprotobuf.a -o protoc.wasm
          wasmtime protoc.wasm --version

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: protoc.wasm
          path: protobuf-wasm/protoc.wasm