name: CI

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Clone emscripten-core/emsdk
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: emscripten-core/emsdk
          path: emsdk

      - name: Install emsdk
        working-directory: emsdk
        run: |
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

      - uses: robinraju/release-downloader@v1
        with:
          repository: 'dsyer/protobuf-wasm'
          tarBall: true
          latest: true
          extract: true
          out-file-path: protobuf-wasm

      - name: Build
        working-directory: protobuf-wasm
        run: |
          emcc -Os -I ./include -s STANDALONE_WASM -s EXPORTED_FUNCTIONS="['_main']" ./lib/libprotobuf-c.a ./lib/libprotobuf.a -o protoc.wasm
          curl https://wasmtime.dev/install.sh -sSf | bash
          wasmtime protoc.wasm --version

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: protoc.wasm
          path: protobuf-wasm/protoc.wasm