name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update && export DEBIAN_FRONTEND=noninteractive \
          && sudo apt-get -y install --no-install-recommends autoconf automake libtool curl make g++ unzip emscripten pkg-config libprotobuf-dev libprotoc-dev protobuf-compiler libprotobuf-c-dev protobuf-c-compiler bzip2 lbzip2 xz-utils nodejs

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: protocolbuffers/protobuf
        ref: v3.12.4
        path: build/protobuf

    - name: Build Protobuf
      working-directory: build/protobuf
      run: |
        ./autogen.sh
        emconfigure ./configure --host=none-none-none
        emmake make
        find . -name \*.a

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: protobuf-c/protobuf-c
        path: build/protobuf-c

    - name: Download Protobuf-c binary
      uses: robinraju/release-downloader@v1
      with:
        repository: 'protobuf-c/protobuf-c'
        tag: 'v1.5.0'
        tarBall: true
        extract: true
        out-file-path: 'build/protobuf-c/protoc-c'

    - name: Build Protobuf-c
      working-directory: build/protobuf-c
      run: |
        ./autogen.sh
        EMMAKEN_CFLAGS=-I../protobuf/src EM_PKG_CONFIG_PATH=../protobuf emconfigure ./configure --host=none-none-none
        EMMAKEN_CFLAGS='-I../protobuf/src -L../protobuf/src/.libs' emmake make
        find . -name \*.a